name: Deploy Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      project_name:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true
      AWS_DEPLOY_ROLE:
        required: true

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ${{ inputs.aws_region }}
          role-session-name: github-actions-${{ inputs.environment }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Deploy infrastructure
        run: |
          cd terraform/aws/infrastructure/environments/${{ inputs.environment }}
          terraform init
          terraform plan -out=plan.tfplan \
            -var="aws_region=${{ inputs.aws_region }}" \
            -var="project_name=${{ inputs.project_name }}" \
            -var="environment=${{ inputs.environment }}"
          terraform apply plan.tfplan