name: Configure AWS Credentials

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  credentials:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::960452239030:role/GitHubAction
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: github-actions-${{ inputs.environment }}