name: Deploy Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.8.1

      - name: Deploy infrastructure
        run: |
          cd terraform/aws/infrastructure/${{ inputs.environment }}
          terraform init
          terraform plan -out=plan.tfplan
          terraform apply plan.tfplan