name: Deploy Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      project_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Deploy infrastructure
        run: |
          cd terraform/aws/infrastructure/environments/${{ inputs.environment }}
          terraform init
          terraform plan -out=plan.tfplan \
            -var="aws_region=${{ inputs.aws_region }}" \
            -var="project_name=${{ inputs.project_name }}" \
            -var="environment=${{ inputs.environment }}"
          terraform apply plan.tfplan