on:
  push:
    branches:
      - '**'

jobs:
  deploy-infra:
    uses: ./.github/workflows/aws_deploy_infra.yaml
    with:
      environment: development
      project_name: ${{ vars.PROJECT_NAME }}
      aws_region: ${{ vars.AWS_REGION }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEPLOY_ROLE: ${{ secrets.AWS_DEPLOY_ROLE }}
