on:
  push:
    branches:
      - '**'

jobs:
  deploy-infra:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/aws_deploy_infra.yaml
    with:
      environment: development
      project_name: gorillionaire
      aws_region: us-east-1
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEPLOY_ROLE: ${{ secrets.AWS_DEPLOY_ROLE }}
