on:
  push:
    branches:
      - '**'
permissions:
  id-token: write
  contents: read

jobs:
  configure-aws:
    uses: ./.github/workflows/aws_credentials.yaml
    with:
      environment: development

  deploy-infra:
    needs: configure-aws
    uses: ./.github/workflows/aws_deploy_infra.yaml
    with:
      environment: development
