on:
  push:
    branches:
      - '**'


jobs:
  configure-aws:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/aws_credentials.yaml
    with:
      environment: development
      aws_region: ${{ vars.AWS_REGION }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEPLOY_ROLE: ${{ secrets.AWS_DEPLOY_ROLE }}

  deploy-infra:
    needs: configure-aws
    uses: ./.github/workflows/aws_deploy_infra.yaml
    with:
      environment: development
      aws_region: ${{ vars.AWS_REGION }}
      project_name: ${{ vars.PROJECT_NAME }}
